/**
 *
 * $Id$
 */
package it.univaq.flyaq.behaviour.validation;

import it.univaq.flyaq.behaviour.Coordinate;

/**
 * A sample validator interface for {@link it.univaq.flyaq.behaviour.Circle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CircleValidator {
	boolean validate();

	boolean validateTargetPosition(Coordinate value);
	boolean validateDuration(float value);
	boolean validateRadius(float value);
	boolean validateAltitude(float value);
	boolean validateClockwise(boolean value);
}
