/**
 *
 * $Id$
 */
package it.univaq.flyaq.behaviour.validation;

import it.univaq.flyaq.behaviour.Coordinate;
import it.univaq.flyaq.behaviour.Move;
import it.univaq.flyaq.behaviour.MoveTransition;
import it.univaq.flyaq.behaviour.Slot;
import it.univaq.flyaq.behaviour.TravelMode;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link it.univaq.flyaq.behaviour.Drone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DroneValidator {
	boolean validate();

	boolean validateTypeName(String value);
	boolean validateHome(Coordinate value);
	boolean validateMovements(EList<Move> value);
	boolean validateMoveTransitions(EList<MoveTransition> value);
	boolean validateSlots(EList<Slot> value);
	boolean validateTravelMode(TravelMode value);
}
