/**
 *
 * $Id$
 */
package it.univaq.flyaq.mission.validation;

import it.univaq.flyaq.mission.Coordinate;

/**
 * A sample validator interface for {@link it.univaq.flyaq.mission.Drone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DroneValidator {
	boolean validate();

	boolean validateHome(Coordinate value);
	boolean validateType(String value);

	boolean validateReturnHome(boolean value);
}
