/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/Desktop/FLYAQ/flyaq_ws/src/flyaq/msg/Behaviour.msg
 *
 */


#ifndef FLYAQ_MESSAGE_BEHAVIOUR_H
#define FLYAQ_MESSAGE_BEHAVIOUR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <flyaq/Drone.h>

namespace flyaq
{
template <class ContainerAllocator>
struct Behaviour_
{
  typedef Behaviour_<ContainerAllocator> Type;

  Behaviour_()
    : name()
    , crs()
    , drones()  {
    }
  Behaviour_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , crs(_alloc)
    , drones(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _crs_type;
  _crs_type crs;

   typedef std::vector< ::flyaq::Drone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::flyaq::Drone_<ContainerAllocator> >::other >  _drones_type;
  _drones_type drones;




  typedef boost::shared_ptr< ::flyaq::Behaviour_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyaq::Behaviour_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Behaviour_

typedef ::flyaq::Behaviour_<std::allocator<void> > Behaviour;

typedef boost::shared_ptr< ::flyaq::Behaviour > BehaviourPtr;
typedef boost::shared_ptr< ::flyaq::Behaviour const> BehaviourConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyaq::Behaviour_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyaq::Behaviour_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flyaq

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'flyaq': ['/home/viki/Desktop/FLYAQ/flyaq_ws/src/flyaq/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flyaq::Behaviour_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyaq::Behaviour_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyaq::Behaviour_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyaq::Behaviour_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyaq::Behaviour_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyaq::Behaviour_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyaq::Behaviour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b9d03cec42c32ed5c6a48197516edf1";
  }

  static const char* value(const ::flyaq::Behaviour_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b9d03cec42c32edULL;
  static const uint64_t static_value2 = 0x5c6a48197516edf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::flyaq::Behaviour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyaq/Behaviour";
  }

  static const char* value(const ::flyaq::Behaviour_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyaq::Behaviour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string crs\n\
Drone[] drones\n\n\n\
================================================================================\n\
MSG: flyaq/Drone\n\
string name\n\
string type_name\n\
Coordinate home\n\
Move[] movements\n\
MoveTransition[] move_transitions\n\
string[] slot_names\n\
int8 SAFE = 0\n\
int8 NORMAL = 1\n\
int8 AGGRESSIVE = 2\n\
int8 travel_mode # enumerated above\n\
================================================================================\n\
MSG: flyaq/Coordinate\n\
float32 latitude\n\
float32 longitude\n\
float32 altitude\n\
float32 heading\n\n\n\n\
================================================================================\n\
MSG: flyaq/Move\n\
string name\n\
int8 START = 0\n\
int8 STOP = 1\n\
int8 TAKE_OFF = 2\n\
int8 LAND = 3\n\
int8 GO_TO = 4\n\
int8 HOVER = 5\n\
int8 CIRCLE = 6\n\
int8 HEAD_TO = 7\n\
int8 type # enumerate above\n\
Action[] pre_actions\n\
Action[] post_actions\n\
float32 altitude # filled only in case of TakeOff move\n\
Coordinate target_position # filled only in case of GoTo or Circle moves\n\
int8 DIRECT = 0\n\
int8 HORIZONTAL_FIRST = 1\n\
int8 VERTICAL_FIRST = 2\n\
int8 strategy # enumerated above, filled only in case of GoTo move\n\
duration duration # filled only in case of Hover or Circle moves\n\
float32 radius # filled only in case of Circle move\n\
float32 circle_altitude # filled only in case of Circle move\n\
bool clockwise # filled only in case of Circle move\n\
float32 direction # filled only in case of HeadTo move \n\n\
================================================================================\n\
MSG: flyaq/Action\n\
string name\n\
int8 DEVICE = 0\n\
int8 FEEDBACK = 1\n\n\
int8 CHECK = 2\n\n\
int8 UNICAST_NOTIFY = 3\n\n\
int8 MULTICAST_NOTIFY = 4\n\n\
int8 BROADCAST_NOTIFY = 5\n\n\
int8 type # enumerate above\n\n\
string action_name # filled only in case of DeviceAction and Feedback\n\n\
Parameter[] parameters # filled only in case of DeviceAction and Feedback\n\n\
string slot_name # filled only in case of Notify (any kind) or CheckNotification\n\n\
string[] receivers_name # filled only in case of MulticastNotify or UnicastNotify\n\n\n\
================================================================================\n\
MSG: flyaq/Parameter\n\
string key\n\
string value\n\n\
================================================================================\n\
MSG: flyaq/MoveTransition\n\
bool is_choice # true if the move transition is a Choice move transition\n\
string wait_for_slot_name\n\
string from_move_name\n\
string to_move_name\n\
bool fluid\n\
string condition_identifier # filled only in case of Choice move transition\n\
string false_branch_move_name # filled only in case of Choice move transition\n\n\
";
  }

  static const char* value(const ::flyaq::Behaviour_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyaq::Behaviour_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.crs);
      stream.next(m.drones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Behaviour_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyaq::Behaviour_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flyaq::Behaviour_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "crs: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.crs);
    s << indent << "drones[]" << std::endl;
    for (size_t i = 0; i < v.drones.size(); ++i)
    {
      s << indent << "  drones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::flyaq::Drone_<ContainerAllocator> >::stream(s, indent + "    ", v.drones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLYAQ_MESSAGE_BEHAVIOUR_H
