/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/Desktop/FLYAQ/flyaq_ws/src/flyaq/msg/CommandReturn.msg
 *
 */


#ifndef FLYAQ_MESSAGE_COMMANDRETURN_H
#define FLYAQ_MESSAGE_COMMANDRETURN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flyaq
{
template <class ContainerAllocator>
struct CommandReturn_
{
  typedef CommandReturn_<ContainerAllocator> Type;

  CommandReturn_()
    : outcome(0)
    , message()
    , drone()  {
    }
  CommandReturn_(const ContainerAllocator& _alloc)
    : outcome(0)
    , message(_alloc)
    , drone(_alloc)  {
    }



   typedef int8_t _outcome_type;
  _outcome_type outcome;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _drone_type;
  _drone_type drone;


    enum { FAIL = 0 };
     enum { SUCCESS = 1 };
 

  typedef boost::shared_ptr< ::flyaq::CommandReturn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyaq::CommandReturn_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct CommandReturn_

typedef ::flyaq::CommandReturn_<std::allocator<void> > CommandReturn;

typedef boost::shared_ptr< ::flyaq::CommandReturn > CommandReturnPtr;
typedef boost::shared_ptr< ::flyaq::CommandReturn const> CommandReturnConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyaq::CommandReturn_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyaq::CommandReturn_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flyaq

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'flyaq': ['/home/viki/Desktop/FLYAQ/flyaq_ws/src/flyaq/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flyaq::CommandReturn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyaq::CommandReturn_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyaq::CommandReturn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyaq::CommandReturn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyaq::CommandReturn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyaq::CommandReturn_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyaq::CommandReturn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb5553c5ccbc2bab658bdc4f34667302";
  }

  static const char* value(const ::flyaq::CommandReturn_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb5553c5ccbc2babULL;
  static const uint64_t static_value2 = 0x658bdc4f34667302ULL;
};

template<class ContainerAllocator>
struct DataType< ::flyaq::CommandReturn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyaq/CommandReturn";
  }

  static const char* value(const ::flyaq::CommandReturn_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyaq::CommandReturn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 FAIL = 0\n\
int8 SUCCESS = 1\n\
int8 outcome # enumerate above\n\
string message\n\
string drone # the drone that executed the command, can be also NONE\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::flyaq::CommandReturn_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyaq::CommandReturn_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outcome);
      stream.next(m.message);
      stream.next(m.drone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommandReturn_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyaq::CommandReturn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flyaq::CommandReturn_<ContainerAllocator>& v)
  {
    s << indent << "outcome: ";
    Printer<int8_t>::stream(s, indent + "  ", v.outcome);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "drone: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.drone);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLYAQ_MESSAGE_COMMANDRETURN_H
