/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/Desktop/FLYAQ/flyaq_ws/src/flyaq/msg/MoveTransition.msg
 *
 */


#ifndef FLYAQ_MESSAGE_MOVETRANSITION_H
#define FLYAQ_MESSAGE_MOVETRANSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flyaq
{
template <class ContainerAllocator>
struct MoveTransition_
{
  typedef MoveTransition_<ContainerAllocator> Type;

  MoveTransition_()
    : is_choice(false)
    , wait_for_slot_name()
    , from_move_name()
    , to_move_name()
    , fluid(false)
    , condition_identifier()
    , false_branch_move_name()  {
    }
  MoveTransition_(const ContainerAllocator& _alloc)
    : is_choice(false)
    , wait_for_slot_name(_alloc)
    , from_move_name(_alloc)
    , to_move_name(_alloc)
    , fluid(false)
    , condition_identifier(_alloc)
    , false_branch_move_name(_alloc)  {
    }



   typedef uint8_t _is_choice_type;
  _is_choice_type is_choice;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _wait_for_slot_name_type;
  _wait_for_slot_name_type wait_for_slot_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _from_move_name_type;
  _from_move_name_type from_move_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _to_move_name_type;
  _to_move_name_type to_move_name;

   typedef uint8_t _fluid_type;
  _fluid_type fluid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _condition_identifier_type;
  _condition_identifier_type condition_identifier;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _false_branch_move_name_type;
  _false_branch_move_name_type false_branch_move_name;




  typedef boost::shared_ptr< ::flyaq::MoveTransition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flyaq::MoveTransition_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MoveTransition_

typedef ::flyaq::MoveTransition_<std::allocator<void> > MoveTransition;

typedef boost::shared_ptr< ::flyaq::MoveTransition > MoveTransitionPtr;
typedef boost::shared_ptr< ::flyaq::MoveTransition const> MoveTransitionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flyaq::MoveTransition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flyaq::MoveTransition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flyaq

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'flyaq': ['/home/viki/Desktop/FLYAQ/flyaq_ws/src/flyaq/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flyaq::MoveTransition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flyaq::MoveTransition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyaq::MoveTransition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flyaq::MoveTransition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyaq::MoveTransition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flyaq::MoveTransition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flyaq::MoveTransition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6b577bdbfc0416bf6dfa5e8a4570219";
  }

  static const char* value(const ::flyaq::MoveTransition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6b577bdbfc0416bULL;
  static const uint64_t static_value2 = 0xf6dfa5e8a4570219ULL;
};

template<class ContainerAllocator>
struct DataType< ::flyaq::MoveTransition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flyaq/MoveTransition";
  }

  static const char* value(const ::flyaq::MoveTransition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flyaq::MoveTransition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_choice # true if the move transition is a Choice move transition\n\
string wait_for_slot_name\n\
string from_move_name\n\
string to_move_name\n\
bool fluid\n\
string condition_identifier # filled only in case of Choice move transition\n\
string false_branch_move_name # filled only in case of Choice move transition\n\n\
";
  }

  static const char* value(const ::flyaq::MoveTransition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flyaq::MoveTransition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_choice);
      stream.next(m.wait_for_slot_name);
      stream.next(m.from_move_name);
      stream.next(m.to_move_name);
      stream.next(m.fluid);
      stream.next(m.condition_identifier);
      stream.next(m.false_branch_move_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveTransition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flyaq::MoveTransition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flyaq::MoveTransition_<ContainerAllocator>& v)
  {
    s << indent << "is_choice: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_choice);
    s << indent << "wait_for_slot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.wait_for_slot_name);
    s << indent << "from_move_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.from_move_name);
    s << indent << "to_move_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.to_move_name);
    s << indent << "fluid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fluid);
    s << indent << "condition_identifier: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.condition_identifier);
    s << indent << "false_branch_move_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.false_branch_move_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLYAQ_MESSAGE_MOVETRANSITION_H
