/**
 *
 * $Id$
 */
package it.univaq.flyaq.drone.validation;

import it.univaq.flyaq.drone.Battery;
import it.univaq.flyaq.drone.Device;
import it.univaq.flyaq.drone.FlightPerformance;
import it.univaq.flyaq.drone.Memory;
import it.univaq.flyaq.drone.Processor;
import it.univaq.flyaq.drone.ROSDriver;
import it.univaq.flyaq.drone.Size;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link it.univaq.flyaq.drone.Drone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DroneValidator {
	boolean validate();

	boolean validateSize(Size value);
	boolean validateFlightPerf(FlightPerformance value);
	boolean validateBatteries(EList<Battery> value);
	boolean validateOnBoardObstacleAvoidance(boolean value);
	boolean validateMinVoltage(float value);
	boolean validateMaxVoltage(float value);
	boolean validateMaxPowerConsumption(float value);
	boolean validateGiro(boolean value);
	boolean validateGps(boolean value);
	boolean validateAccelerometer(boolean value);
	boolean validateMagnetometer(boolean value);
	boolean validateBarometer(boolean value);
	boolean validateCommunicationRange(float value);
	boolean validateDataRate(int value);
	boolean validateRadioFrequency(int value);
	boolean validateProcessors(EList<Processor> value);
	boolean validateMemory(EList<Memory> value);
	boolean validateDataEquipment(EList<Device> value);
	boolean validateRosDriver(ROSDriver value);
	boolean validateIcon(String value);
}
