/**
 *
 * $Id$
 */
package it.univaq.flyaq.drone.validation;

import it.univaq.flyaq.drone.LaunchType;

/**
 * A sample validator interface for {@link it.univaq.flyaq.drone.FlightPerformance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlightPerformanceValidator {
	boolean validate();

	boolean validateLaunchType(LaunchType value);
	boolean validateMinSpeed(int value);
	boolean validateMaxSpeed(int value);
	boolean validateMinAcceleration(int value);
	boolean validateMaxAcceleration(int value);
	boolean validateMaxAltitude(int value);
	boolean validateMaxTurnRate(float value);
	boolean validateMinTurnRate(float value);
	boolean validateMaxClimbRate(float value);
	boolean validateMaxDescendRate(float value);
	boolean validatePositionHold(float value);
	boolean validateMaxPayload(int value);
	boolean validateMaxFlightTime(int value);
	boolean validateMaxFlightTimeWithMaxPayload(int value);
	boolean validateMinOperatingTemperature(float value);
	boolean validateMaxOperatingTemperature(float value);
}
