/**
 *
 * $Id$
 */
package it.univaq.flyaq.drone.validation;

import it.univaq.flyaq.drone.MemoryType;

/**
 * A sample validator interface for {@link it.univaq.flyaq.drone.Memory}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemoryValidator {
	boolean validate();

	boolean validateType(MemoryType value);
	boolean validateSubType(String value);
	boolean validateSize(int value);
}
