/**
 *
 * $Id$
 */
package it.univaq.flyaq.extensions.extension1.validation;

import it.univaq.flyaq.extensions.extension1.GoToType;

/**
 * A sample validator interface for {@link it.univaq.flyaq.extensions.extension1.GoToTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GoToTaskValidator {
	boolean validate();

	boolean validateType(GoToType value);
}
